language: php

env:
  global:
    - ES_VER=0.19.11
    - ES_MAPPER_ATTACHMENTS_VER=1.6.0

before_script:
  - ./test/bin/install_php_memcache.sh
  - ./test/bin/run_elasticsearch.sh

script: phpunit -c test/
