language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - ES_VER=0.90.0 ES_MAPPER_ATTACHMENTS_VER=1.6.0 ES_TRANSPORT_THRIFT_VER=1.4.0 ES_REQUIRE=dev
  - ES_VER=0.90.0 ES_MAPPER_ATTACHMENTS_VER=1.6.0 ES_TRANSPORT_THRIFT_VER=1.4.0 ES_REQUIRE=no-dev

before_script:
  - composer self-update
  - composer --{ES_REQUIRE} --prefer-source install
  - ./test/bin/install_php_memcache.sh
  - ./test/bin/run_elasticsearch.sh

script: phpunit -c test/
